/**
 * seed-reset.ts — canonical reset-to-seed for E2E (GH #310).
 *
 * The canon is an auto-generated SQL file (scripts/gen_seed_canon.py) that
 * scripts/e2e-shard-start.sh snapshots ONCE per stack, right after the seed
 * subprocess — the only moment the DB is guaranteed pristine. This module
 * applies that file:
 *   - `globalSetup.ts` (boot: a long-lived stack may start a later run on a
 *     garbage DB from the previous run — boot application restores the canon
 *     before the #152 seed-contract check and the logins below it);
 *   - the per-test wrapper fixture (reset before EVERY test, incl. retries).
 *
 * Policy (GH #310, spec rev 4): mutations of ANY seed row are allowed — the
 * reset restores every table and every field (incl. created_at/updated_at
 * stamps and relative-week ev_* activities) from the canon. Two exceptions
 * BY DESIGN:
 *   - `audit_logs` — append-only journal, never wiped;
 *   - `sessions`   — the auth-cookie invariant (GH #252 §3.1): storageState
 *                    logins from globalSetup must survive per-test resets.
 *
 * The canon file is data-only (DELETE + INSERT in one transaction with
 * `BEGIN IMMEDIATE`, so the write lock is taken up front — no WAL upgrade
 * deadlock against the LIVE backend pool) and is applied through the shared
 * busy-wait retry wrapper, same as every other sqlite3 CLI call in the suite.
 */
import fs from 'fs';
import path from 'path';

import { sqliteExecWithRetry } from './sqlite-exec';
import { resolveTestDbPath } from '../lib/db-path';

/**
 * Resolve the test DB path AT CALL TIME — never at module load (env vars
 * are set by the shard script / test runner and may change between
 * import and call). Delegates to the shared GH #209 resolver
 * (e2e/lib/db-path.ts): SHARD_ID → canonical shard DB; a SHARD_ID ×
 * TEST_DB_PATH conflict is a loud error (no silent precedence).
 */
export function resolveSeedDbPath(): string {
  return resolveTestDbPath({
    shardId: process.env.SHARD_ID,
    testDbPath: process.env.TEST_DB_PATH,
  });
}

/**
 * Path of the canonical reset script for the resolved test DB. The shard
 * stack generates it at `<db>.canon.sql` (gen_seed_canon.py) — per-shard by
 * construction, deterministic, stable for the lifetime of the stack.
 */
export function resolveSeedCanonPath(): string {
  return `${resolveSeedDbPath()}.canon.sql`;
}

/**
 * GH #262 §6 (E2E infra) — resolve the TEST-SCOPED `FILES_DIR` root at call
 * time, mirroring {@link resolveSeedDbPath}'s shard/env/default rules so the
 * Playwright process and the shard backend agree on the SAME avatars dir:
 *   SHARD_ID set          → backend/test_files_shard{id}
 *   else TEST_FILES_DIR    → as-is, relative resolved against process CWD
 *   else FILES_DIR         → as-is (the env the backend reads, config.py)
 *   else                  → backend/files (backend default `./files` from the
 *                            backend cwd, where uvicorn runs)
 *
 * `scripts/e2e-shard-start.sh` exports FILES_DIR to the shard-scoped path so
 * the backend serves uploads from there; this resolver reproduces that path
 * for the wipe below WITHOUT importing the backend settings.
 */
export function resolveTestFilesDir(): string {
  const shardId = process.env.SHARD_ID;
  if (shardId) {
    return path.resolve(__dirname, `../../../../backend/test_files_shard${shardId}`);
  }
  const fromEnv = process.env.TEST_FILES_DIR || process.env.FILES_DIR;
  if (fromEnv) return path.resolve(fromEnv);
  return path.resolve(__dirname, '../../../../backend/files');
}

/**
 * GH #262 §6 — wipe the avatars storage dir TOGETHER with the DB reset so a
 * portrait uploaded by one test never leaks into the next (seed users carry
 * NO avatars, spec §6, so the canonical post-reset state is an empty dir).
 * Removes `FILES_DIR/avatars` entirely; the backend re-creates it on the next
 * upload (services/files.py mkdir) and on boot (main.py lifespan). Best-effort:
 * a missing dir is not an error.
 */
export function wipeAvatarsDir(): void {
  const avatars = path.join(resolveTestFilesDir(), 'avatars');
  fs.rmSync(avatars, { recursive: true, force: true });
}

/**
 * Reset the test DB to canonical seed state by applying the canon file
 * through the shared busy-wait retry wrapper (same lock-retry semantics as
 * every other sqlite3 CLI call in the suite). A missing canon file is a
 * LOUD error naming the fix: the stack must be started via
 * scripts/e2e-shard-start.sh, which generates the canon after seeding.
 */
export function resetToSeed(): string {
  const canonPath = resolveSeedCanonPath();
  if (!fs.existsSync(canonPath)) {
    throw new Error(
      `[seed-canon] Canonical reset script not found: ${canonPath}. ` +
        `It is generated by scripts/e2e-shard-start.sh (gen_seed_canon.py) right after ` +
        `seeding. Start the stack via \`bash scripts/test-all.sh\` (CI/local) or ` +
        `\`SHARD_ID=N ... bash scripts/e2e-shard-start.sh\` (standalone), then retry.`,
    );
  }
  return sqliteExecWithRetry(`sqlite3 "${resolveSeedDbPath()}" ".read '${canonPath}'"`);
}

/**
 * Structural subset of Playwright's `TestInfo` — pass the fixture's
 * `testInfo` directly (spec §3.2 calls `await snapshotDb(testInfo)`).
 * Exported so the fixture (and tests) can depend on it.
 */
export interface SnapshotDbTestInfo {
  outputDir: string;
}

/**
 * Save a consistent DB snapshot into `testInfo.outputDir` (spec D7 / §3.2):
 * on a retry attempt the fixture snapshots the DB BEFORE resetting, so the
 * pre-reset state survives forensics even though the next reset wipes it.
 * `.backup` is consistent under WAL. Synchronous — the fixture awaits it.
 *
 * @param testInfo Playwright TestInfo-compatible object; its outputDir
 *                 is created if missing
 */
export function snapshotDb(testInfo: SnapshotDbTestInfo): string {
  fs.mkdirSync(testInfo.outputDir, { recursive: true });
  const snapshotPath = path.join(testInfo.outputDir, 'db-before-reset.sqlite');
  return sqliteExecWithRetry(
    `sqlite3 "${resolveSeedDbPath()}" ".backup '${snapshotPath}'"`,
  );
}
