"""add user_settings table

Revision ID: 25569161a522
Revises: 93d06343a4bb
Create Date: 2026-06-13 19:31:01.021222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25569161a522'
down_revision: Union[str, Sequence[str], None] = '93d06343a4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id"), unique=True, nullable=False),
        sa.Column("theme", sa.String(10), nullable=False, server_default="light"),
        sa.Column("language", sa.String(5), nullable=False, server_default="ru"),
        sa.Column("column_order_masters", sa.Text, nullable=False, server_default="[]"),
        sa.Column("column_order_locations", sa.Text, nullable=False, server_default="[]"),
        sa.Column("id", sa.String(36), primary_key=True, nullable=False),
        sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.text("1")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_settings")
    # ### end Alembic commands ###
