"""make service max_age nullable

Revision ID: 275ba490cab8
Revises: 4c7aaa708a63
Create Date: 2026-06-16 17:54:12.875156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275ba490cab8'
down_revision: Union[str, Sequence[str], None] = '4c7aaa708a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('max_age',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('max_age',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
