"""add short_title to locations

Revision ID: 4c7aaa708a63
Revises: 25569161a522
Create Date: 2026-06-16 12:15:59.582566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7aaa708a63'
down_revision: Union[str, Sequence[str], None] = '25569161a522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table: str, column: str) -> bool:
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return column in [col["name"] for col in inspector.get_columns(table)]


def upgrade() -> None:
    """Upgrade schema."""
    # Guard: initial migration already creates locations with short_title.
    if not _column_exists("locations", "short_title"):
        with op.batch_alter_table('locations', schema=None) as batch_op:
            batch_op.add_column(sa.Column('short_title', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('short_title')

    # ### end Alembic commands ###
