"""add custom_price to records

Revision ID: c2d4ed6da43f
Revises: ce42b37ee405
Create Date: 2026-06-05 10:44:02.367980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d4ed6da43f'
down_revision: Union[str, Sequence[str], None] = 'ce42b37ee405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_price', sa.Integer(), nullable=True))

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('visitor_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('visitor_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('custom_price')

    # ### end Alembic commands ###
