"""add custom_price to records

Revision ID: c2d4ed6da43f
Revises: ce42b37ee405
Create Date: 2026-06-05 10:44:02.367980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d4ed6da43f'
down_revision: Union[str, Sequence[str], None] = 'ce42b37ee405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table: str, column: str) -> bool:
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return column in [col["name"] for col in inspector.get_columns(table)]


def upgrade() -> None:
    """Upgrade schema."""
    # Guard: initial migration already creates records with custom_price
    # and visits with nullable visitor_id.
    if not _column_exists("records", "custom_price"):
        with op.batch_alter_table('records', schema=None) as batch_op:
            batch_op.add_column(sa.Column('custom_price', sa.Integer(), nullable=True))

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    visitor_id_col = [c for c in inspector.get_columns("visits") if c["name"] == "visitor_id"]
    if visitor_id_col and not visitor_id_col[0]["nullable"]:
        with op.batch_alter_table('visits', schema=None) as batch_op:
            batch_op.alter_column('visitor_id',
                   existing_type=sa.VARCHAR(length=36),
                   nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('visitor_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('custom_price')

    # ### end Alembic commands ###
