"""make client fields nullable

Revision ID: ce42b37ee405
Revises: 4af69d9eff31
Create Date: 2026-06-04 20:07:02.645410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce42b37ee405'
down_revision: Union[str, Sequence[str], None] = '4af69d9eff31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_is_nullable(table: str, column: str) -> bool:
    """Check if a column is already nullable."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    for col in inspector.get_columns(table):
        if col["name"] == column:
            return col["nullable"]
    return False


def upgrade() -> None:
    """Upgrade schema."""
    # Guard: initial migration already creates clients with nullable fields.
    # These ALTERs are no-ops when running from a fresh DB.
    nullable_cols = [
        ("clients", "name", sa.VARCHAR(length=200)),
        ("clients", "phone", sa.VARCHAR(length=20)),
        ("clients", "channel", sa.VARCHAR(length=50)),
    ]
    for table, column, col_type in nullable_cols:
        if not _column_is_nullable(table, column):
            with op.batch_alter_table(table, schema=None) as batch_op:
                batch_op.alter_column(column, existing_type=col_type, nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('channel',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
