#!/usr/bin/env python3
"""Generate the canonical seed-reset SQL script for e2e (GH #310).

Runs at shard-stack startup, right after the seed subprocess (see
scripts/e2e-shard-start.sh): the DB is guaranteed to hold the pristine
seed at that moment, so the snapshot it produces IS the canon. The
Playwright side (fixtures/seed-reset.ts) applies this file before every
test instead of a hand-maintained SQL statement.

Output file layout (one statement stream, applied by `sqlite3` CLI):

    PRAGMA busy_timeout=5000;
    PRAGMA foreign_keys=OFF;
    BEGIN IMMEDIATE;
    DELETE FROM "<table>";   -- every table except the blacklist
    INSERT INTO "<table>" ("<col>", ...) VALUES (...);  -- seed rows
    COMMIT;

Blacklist (spec rev 4 §Решение п.3):
  - audit_logs — append-only journal, never wiped by design;
  - sessions   — the auth-cookie invariant (GH #252 §3.1): storageState
                 logins from globalSetup must survive per-test resets.

`BEGIN IMMEDIATE` takes the write lock up front (no WAL upgrade deadlock
with the live backend pool); row order is pinned by `ORDER BY rowid` so
the file — and therefore every reset — is byte-deterministic for a given
seed. The write is atomic (tmp file + os.replace); a stale file from a
previous stack is removed up front so a failed generation never leaves a
usable-but-stale canon behind.

Usage: python3 gen_seed_canon.py <db-path> <out-path>
"""
import os
import sqlite3
import sys
import tempfile

BLACKLIST_TABLES = {"audit_logs", "sessions"}


def sql_literal(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, bytes):
        return "X'" + value.hex() + "'"
    return "'" + str(value).replace("'", "''") + "'"


def list_tables(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        "SELECT name FROM sqlite_master "
        "WHERE type = 'table' AND name NOT LIKE 'sqlite_%' "
        "ORDER BY name"
    ).fetchall()
    return [r[0] for r in rows if r[0] not in BLACKLIST_TABLES]


def dump_table(conn: sqlite3.Connection, table: str, out) -> None:
    cols = [r[1] for r in conn.execute(f'PRAGMA table_info("{table}")').fetchall()]
    if not cols:
        return
    col_list = ", ".join(f'"{c}"' for c in cols)
    for row in conn.execute(f'SELECT * FROM "{table}" ORDER BY rowid'):
        values = ", ".join(sql_literal(v) for v in row)
        out.write(f'INSERT INTO "{table}" ({col_list}) VALUES ({values});\n')


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <db-path> <out-path>")
    db_path, out_path = sys.argv[1], sys.argv[2]

    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        tables = list_tables(conn)
        if not tables:
            sys.exit(f"[gen_seed_canon] no tables found in {db_path} — was the stack seeded?")

        # Remove a stale canon up front: a failed generation must abort the
        # stack (set -e in the shard script), never silently keep the old file.
        try:
            os.remove(out_path)
        except FileNotFoundError:
            pass

        out_dir = os.path.dirname(os.path.abspath(out_path))
        fd, tmp_path = tempfile.mkstemp(dir=out_dir, prefix=".canon.", suffix=".sql")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as out:
                out.write("-- Canonical seed reset (auto-generated by gen_seed_canon.py, GH #310)\n")
                out.write("-- Apply to a LIVE non-empty test DB: idempotent DELETE + re-INSERT.\n")
                out.write("-- Exceptions by design: audit_logs (append-only), sessions (auth cookies).\n")
                out.write("PRAGMA busy_timeout=5000;\n")
                out.write("PRAGMA foreign_keys=OFF;\n")
                # WAL + synchronous=NORMAL: no fsync on commit (the reset runs
                # hundreds of times per shard; crash-durability of a throwaway
                # test DB is worthless, lock-safety is fully preserved).
                out.write("PRAGMA synchronous=NORMAL;\n")
                out.write("BEGIN IMMEDIATE;\n")
                for t in tables:
                    out.write(f'DELETE FROM "{t}";\n')
                for t in tables:
                    dump_table(conn, t, out)
                out.write("COMMIT;\n")
            os.replace(tmp_path, out_path)
        except BaseException:
            try:
                os.remove(tmp_path)
            except FileNotFoundError:
                pass
            raise
    finally:
        conn.close()

    size = os.path.getsize(out_path)
    print(f"[gen_seed_canon] canon written: {out_path} ({size} bytes, {len(tables)} tables)")


if __name__ == "__main__":
    main()
