// Re-export all domain types for backward compatibility during migration.
// New code should import directly from '@memo/domain'.
export type {
  Artist,
  Location,
  Studio,
  Service,
  Activity,
  Client,
  Visitor,
  BookingRecord,
  BookingStatus,
  Visit,
  Payment,
  PaymentMethod,
  StampState,
  Filters,
  Conflict,
  FormatPainterState,
  FormatPainterMode,
  ViewMode,
  ChatMessage,
  ServiceRecommendation,
  BookingVisitor,
  BookingStep,
} from '@memo/domain';

// Re-export Zod schemas (values, not types)
export {
  ArtistSchema,
  LocationSchema,
  ServiceSchema,
  ActivitySchema,
  ClientSchema,
  VisitorSchema,
  BookingRecordSchema,
  BookingStatusSchema,
  VisitSchema,
  PaymentSchema,
  PaymentMethodSchema,
  StampStateSchema,
  FiltersSchema,
  ConflictSchema,
  FormatPainterStateSchema,
  FormatPainterModeSchema,
  ViewModeSchema,
  ChatMessageSchema,
  ServiceRecommendationSchema,
  BookingVisitorSchema,
  BookingStepSchema,
} from '@memo/domain';
