/**
 * seed-reset.test.ts — Unit tests for the shared e2e seed-reset module.
 *
 * GH #252 created the module with a hand-maintained RESET_SQL; GH #310
 * replaced it with the auto-generated canon (`scripts/gen_seed_canon.py`
 * snapshots the pristine seed at stack startup into `<db>.canon.sql`;
 * `resetToSeed()` applies it before every test). These tests verify,
 * against a REAL throwaway SQLite DB (sqlite3 CLI + the REAL generator):
 *
 *   1. call-time DB path resolution order: SHARD_ID → TEST_DB_PATH → default
 *      (unchanged from #209);
 *   2. resetToSeed() applies the canon: mutated seed rows are fully
 *      restored (status/sort_order/titles/staff_positions), deleted seed
 *      rows resurrect, non-seed (UUID) rows vanish, user_settings wiped;
 *   3. the two by-design exceptions survive: audit_logs, sessions;
 *   4. a missing canon file is a LOUD error naming the stack script.
 *
 * Uses TEST_DB_PATH pointing at a temp file — no backend, no shard stack;
 * the canon is generated by the real python3 generator against that temp
 * DB (python3 is available on every runner image this suite uses).
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { execSync } from 'child_process';
import fs from 'fs';
import os from 'os';
import path from 'path';

import {
  resolveSeedCanonPath,
  resolveSeedDbPath,
  resolveTestFilesDir,
  resetToSeed,
  wipeAvatarsDir,
} from '../e2e/fixtures/seed-reset';

/** Repo root: __tests__ → admin → frontend → root (3 up), like db-path.ts. */
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
const GEN_SCRIPT = path.join(REPO_ROOT, 'scripts', 'gen_seed_canon.py');

let tmpDir: string;
let dbPath: string;

/** Create a minimal DB shaped like the real schema (only columns under test):
 *  the full transactional + staff domain + the two canon-exception tables. */
function createSchema(db: string) {
  execSync(`sqlite3 "${db}" "
    CREATE TABLE clients (id TEXT PRIMARY KEY, name TEXT);
    CREATE TABLE visitors (id TEXT PRIMARY KEY, client_id TEXT, name TEXT);
    CREATE TABLE activities (id TEXT PRIMARY KEY, title TEXT);
    CREATE TABLE records (id TEXT PRIMARY KEY, activity_id TEXT, client_id TEXT, status TEXT, seats INTEGER);
    CREATE TABLE visits (id TEXT PRIMARY KEY, record_id TEXT);
    CREATE TABLE payments (id TEXT PRIMARY KEY, record_id TEXT, amount INTEGER);
    CREATE TABLE staff (id TEXT PRIMARY KEY, sort_order INTEGER);
    CREATE TABLE masters (staff_id TEXT PRIMARY KEY, specialty TEXT, color TEXT, is_active INTEGER);
    CREATE TABLE positions (id TEXT PRIMARY KEY, title TEXT, is_system INTEGER);
    CREATE TABLE staff_positions (staff_id TEXT, position_id TEXT, PRIMARY KEY (staff_id, position_id));
    CREATE TABLE master_tags (master_id TEXT, tag_id TEXT, PRIMARY KEY (master_id, tag_id));
    CREATE TABLE users (id TEXT PRIMARY KEY, phone TEXT, staff_id TEXT);
    CREATE TABLE user_settings (id TEXT PRIMARY KEY, user_id TEXT, show_archived_masters INTEGER);
    CREATE TABLE locations (id TEXT PRIMARY KEY, sort_order INTEGER);
    CREATE TABLE audit_logs (id TEXT PRIMARY KEY, action TEXT);
    CREATE TABLE sessions (token TEXT PRIMARY KEY, user_id TEXT);
  "`);
}

/** Seed rows in their CANONICAL state (what the shard seed would produce),
 *  then let the test mutate and the canon restore. GH #266: seed sort_order
 *  lives on `staff`; masters is keyed by staff_id. */
function seedCanonical(db: string) {
  execSync(`sqlite3 "${db}" "
    INSERT INTO clients (id, name) VALUES ('c1', 'Seed Client');
    INSERT INTO visitors (id, client_id, name) VALUES ('v1', 'c1', 'Seed Visitor');
    INSERT INTO activities (id, title) VALUES ('ev_0', 'Seed Activity');
    INSERT INTO activities (id, title) VALUES ('ev_fixed_0', 'Seed Fixed Activity');
    INSERT INTO records (id, activity_id, client_id, status, seats) VALUES ('r1', 'ev_0', 'c1', 'visited', 2);
    INSERT INTO visits (id, record_id) VALUES ('v1', 'r1');
    INSERT INTO payments (id, record_id, amount) VALUES ('p1', 'r1', 6000);
    INSERT INTO staff (id, sort_order) VALUES ('m1', 0);
    INSERT INTO staff (id, sort_order) VALUES ('m2', 1);
    INSERT INTO staff (id, sort_order) VALUES ('m7', 5);
    INSERT INTO masters (staff_id, specialty, color, is_active) VALUES ('m1', 'живопись', '#5B8C7A', 1);
    INSERT INTO positions (id, title, is_system) VALUES ('master', 'Мастер', 1);
    INSERT INTO positions (id, title, is_system) VALUES ('admin', 'Администратор', 1);
    INSERT INTO positions (id, title, is_system) VALUES ('smm', 'СММ', 0);
    INSERT INTO staff_positions (staff_id, position_id) VALUES ('m1','master'),('m2','master'),('m3','master'),('m4','master'),('m5','master'),('m7','master');
    INSERT INTO master_tags (master_id, tag_id) VALUES ('m1', 't1');
    INSERT INTO users (id, phone, staff_id) VALUES ('u1', '+79990000001', 'm1');
    INSERT INTO locations (id, sort_order) VALUES ('alpika', 0);
    INSERT INTO locations (id, sort_order) VALUES ('grand', 1);
    INSERT INTO locations (id, sort_order) VALUES ('p1389', 2);
  "`);
}

/** Mutate EVERY domain the old RESET_SQL used to handle point-wise (and the
 *  ones it never could): edited seed fields, deleted seed rows, UUID test
 *  rows, renamed dictionary, detached users, leaked user_settings. */
function pollute(db: string) {
  execSync(`sqlite3 "${db}" "
    UPDATE records SET status='cancelled', seats=5 WHERE id='r1';
    DELETE FROM records WHERE id='r1';
    UPDATE payments SET amount=1 WHERE id='p1';
    UPDATE staff SET sort_order=99 WHERE id IN ('m1','m2','m7');
    UPDATE positions SET title='Master-renamed', is_system=0 WHERE id='master';
    DELETE FROM staff_positions;
    UPDATE locations SET sort_order=42 WHERE id='alpika';
    INSERT INTO clients (id, name) VALUES ('${'x'.repeat(36)}', 'Polluted Client');
    INSERT INTO visitors (id, client_id, name) VALUES ('${'w'.repeat(36)}', 'c1', 'Orphan Visitor');
    INSERT INTO records (id, activity_id, client_id, status, seats) VALUES ('${'y'.repeat(36)}', 'ev_0', 'c1', 'waiting', 1);
    INSERT INTO visits (id, record_id) VALUES ('${'z'.repeat(36)}', 'r1');
    INSERT INTO payments (id, record_id, amount) VALUES ('${'q'.repeat(36)}', 'r1', 123);
    INSERT INTO activities (id, title) VALUES ('evt_something', 'EvT Non-Seed (must go)');
    INSERT INTO staff (id, sort_order) VALUES ('${'u'.repeat(36)}', 100);
    INSERT INTO master_tags (master_id, tag_id) VALUES ('${'u'.repeat(36)}', 'tX');
    INSERT INTO users (id, phone, staff_id) VALUES ('u2', '+79990000099', 'm1');
    INSERT INTO user_settings (id, user_id) VALUES ('s1', 'u1');
    INSERT INTO user_settings (id, user_id) VALUES ('${'s'.repeat(36)}', 'u1');
  "`);
}

function count(db: string, sql: string): number {
  const out = execSync(`sqlite3 "${db}" "${sql}"`, { encoding: 'utf-8' }).trim();
  return parseInt(out, 10) || 0;
}

/** Read a single numeric value; a missing row (empty output) → NaN, so a
 *  value of 0 can never masquerade as an absent row. */
function scalar(db: string, sql: string): number {
  const out = execSync(`sqlite3 "${db}" "${sql}"`, { encoding: 'utf-8' }).trim();
  const n = parseInt(out, 10);
  return Number.isNaN(n) ? NaN : n;
}

describe('resolveSeedDbPath (call-time resolution)', () => {
  const ORIGINAL = { ...process.env };

  beforeEach(() => {
    delete process.env.SHARD_ID;
    delete process.env.TEST_DB_PATH;
  });

  afterEach(() => {
    process.env = { ...ORIGINAL };
  });

  it('throws when SHARD_ID and TEST_DB_PATH CONFLICT (GH #209 — no silent precedence)', () => {
    process.env.SHARD_ID = '3';
    process.env.TEST_DB_PATH = '/tmp/should-conflict.sqlite';
    expect(() => resolveSeedDbPath()).toThrowError(/SHARD_ID/);
  });

  it('SHARD_ID alone anchors at <repo>/backend', () => {
    process.env.SHARD_ID = '3';
    const repoBackend = path.resolve(__dirname, '..', '..', '..', 'backend');
    expect(resolveSeedDbPath()).toBe(path.join(repoBackend, 'test_memo_shard3.db'));
  });

  it('SHARD_ID with a MATCHING TEST_DB_PATH passes quietly (absolute form)', () => {
    process.env.SHARD_ID = '3';
    process.env.TEST_DB_PATH = path.resolve(
      __dirname, '..', '..', '..', 'backend', 'test_memo_shard3.db',
    );
    expect(resolveSeedDbPath()).toBe(process.env.TEST_DB_PATH);
  });

  it('TEST_DB_PATH is used when SHARD_ID is unset', () => {
    process.env.TEST_DB_PATH = '/tmp/custom-test-db.sqlite';
    expect(resolveSeedDbPath()).toBe('/tmp/custom-test-db.sqlite');
  });

  it('falls back to backend/test_memo.db by default', () => {
    const repoBackend = path.resolve(__dirname, '..', '..', '..', 'backend');
    expect(resolveSeedDbPath()).toBe(path.join(repoBackend, 'test_memo.db'));
  });

  it('canon path is <db>.canon.sql (GH #310 — what the shard stack generates)', () => {
    process.env.TEST_DB_PATH = '/tmp/custom-test-db.sqlite';
    expect(resolveSeedCanonPath()).toBe('/tmp/custom-test-db.sqlite.canon.sql');
  });
});

describe('resetToSeed (canon-based, against a real temp SQLite DB)', () => {
  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'seed-reset-test-'));
    dbPath = path.join(tmpDir, 'unit-test-memo.db');
    createSchema(dbPath);
    seedCanonical(dbPath);
    // Generate the canon with the REAL generator, exactly as the shard
    // stack does — right after seeding, while the DB is pristine.
    execSync(`python3 "${GEN_SCRIPT}" "${dbPath}" "${dbPath}.canon.sql"`, { stdio: 'pipe' });
    pollute(dbPath);
    process.env.SHARD_ID = '';
    delete process.env.SHARD_ID;
    process.env.TEST_DB_PATH = dbPath;
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    delete process.env.TEST_DB_PATH;
  });

  it('restores deleted/edited seed rows and removes non-seed rows (total restore)', () => {
    resetToSeed();

    // seed rows survive in canonical state (r1 was BOTH edited and deleted)
    expect(count(dbPath, "SELECT COUNT(*) FROM records WHERE id='r1' AND status='visited' AND seats=2")).toBe(1);
    expect(scalar(dbPath, "SELECT amount FROM payments WHERE id='p1'")).toBe(6000);
    expect(count(dbPath, "SELECT COUNT(*) FROM activities WHERE id IN ('ev_0','ev_fixed_0')")).toBe(2);

    // non-seed rows are gone
    expect(count(dbPath, 'SELECT COUNT(*) FROM clients WHERE length(id) > 3')).toBe(0);
    expect(count(dbPath, 'SELECT COUNT(*) FROM visitors WHERE length(id) > 5')).toBe(0);
    expect(count(dbPath, 'SELECT COUNT(*) FROM records WHERE length(id) > 3')).toBe(0);
    expect(count(dbPath, 'SELECT COUNT(*) FROM visits WHERE length(id) > 3')).toBe(0);
    expect(count(dbPath, 'SELECT COUNT(*) FROM payments WHERE length(id) > 3')).toBe(0);
    expect(count(dbPath, "SELECT COUNT(*) FROM activities WHERE id='evt_something'")).toBe(0);
  });

  it('restores canonical sort_order, dictionary titles and staff_positions', () => {
    resetToSeed();

    expect(scalar(dbPath, "SELECT sort_order FROM staff WHERE id='m1'")).toBe(0);
    expect(scalar(dbPath, "SELECT sort_order FROM staff WHERE id='m2'")).toBe(1);
    expect(scalar(dbPath, "SELECT sort_order FROM staff WHERE id='m7'")).toBe(5);
    expect(scalar(dbPath, "SELECT sort_order FROM locations WHERE id='alpika'")).toBe(0);
    expect(scalar(dbPath, "SELECT sort_order FROM locations WHERE id='grand'")).toBe(1);
    expect(scalar(dbPath, "SELECT sort_order FROM locations WHERE id='p1389'")).toBe(2);
    expect(scalar(dbPath, "SELECT is_system FROM positions WHERE id='master'")).toBe(1);
    expect(execSync(`sqlite3 "${dbPath}" "SELECT title FROM positions WHERE id='master'"`, { encoding: 'utf-8' }).trim()).toBe('Мастер');
    expect(scalar(dbPath, 'SELECT COUNT(*) FROM staff_positions')).toBe(6); // m1–m5, m7
    expect(count(dbPath, `SELECT COUNT(*) FROM staff WHERE id='${'u'.repeat(36)}'`)).toBe(0);
    expect(count(dbPath, `SELECT COUNT(*) FROM master_tags WHERE master_id='${'u'.repeat(36)}'`)).toBe(0);
  });

  it('restores users to seed (non-seed user rows vanish — policy flip of GH #310)', () => {
    resetToSeed();

    // users is no longer "kept but detached" (the pre-#310 compromise): the
    // canon fully restores the table, so the polluter's u2 row is GONE and
    // the seed u1 row is back with its canonical staff_id.
    expect(count(dbPath, "SELECT COUNT(*) FROM users WHERE id='u2'")).toBe(0);
    expect(count(dbPath, "SELECT COUNT(*) FROM users WHERE id='u1' AND staff_id='m1'")).toBe(1);
  });

  it('wipes user_settings whole (GH #267 — persisted toggles must not leak between tests)', () => {
    resetToSeed();

    expect(scalar(dbPath, 'SELECT COUNT(*) FROM user_settings')).toBe(0);
  });

  it('keeps audit_logs and sessions — the two by-design exceptions (GH #310)', () => {
    execSync(`sqlite3 "${dbPath}" "
      INSERT INTO audit_logs (id, action) VALUES ('aud-1', 'TEST');
      INSERT INTO sessions (token, user_id) VALUES ('tok-1', 'u1');
    "`);
    resetToSeed();

    expect(count(dbPath, "SELECT COUNT(*) FROM audit_logs WHERE id='aud-1'")).toBe(1);
    expect(count(dbPath, "SELECT COUNT(*) FROM sessions WHERE token='tok-1'")).toBe(1);
  });

  it('is idempotent (double application is a no-op beyond the first)', () => {
    resetToSeed();
    const before = execSync(`sqlite3 "${dbPath}" ".dump"`, { encoding: 'utf-8' });
    resetToSeed();
    const after = execSync(`sqlite3 "${dbPath}" ".dump"`, { encoding: 'utf-8' });
    expect(after).toBe(before);
  });

  it('throws a LOUD error naming the stack script when the canon file is missing', () => {
    fs.rmSync(`${dbPath}.canon.sql`);
    expect(() => resetToSeed()).toThrowError(/\[seed-canon\][\s\S]*e2e-shard-start\.sh/);
  });
});

describe('resolveTestFilesDir (call-time resolution, GH #262)', () => {
  const ORIGINAL = { ...process.env };

  beforeEach(() => {
    delete process.env.SHARD_ID;
    delete process.env.TEST_FILES_DIR;
    delete process.env.FILES_DIR;
  });

  afterEach(() => {
    process.env = { ...ORIGINAL };
  });

  it('SHARD_ID wins over TEST_FILES_DIR/FILES_DIR and anchors at <repo>/backend', () => {
    process.env.SHARD_ID = '2';
    process.env.TEST_FILES_DIR = '/tmp/should-be-ignored';
    const repoBackend = path.resolve(__dirname, '..', '..', '..', 'backend');
    expect(resolveTestFilesDir()).toBe(path.join(repoBackend, 'test_files_shard2'));
  });

  it('TEST_FILES_DIR is used when SHARD_ID is unset', () => {
    process.env.TEST_FILES_DIR = '/tmp/custom-files';
    expect(resolveTestFilesDir()).toBe('/tmp/custom-files');
  });

  it('FILES_DIR is used when SHARD_ID and TEST_FILES_DIR are unset', () => {
    process.env.FILES_DIR = '/tmp/env-files';
    expect(resolveTestFilesDir()).toBe('/tmp/env-files');
  });

  it('falls back to backend/files by default (backend cwd-relative ./files)', () => {
    const repoBackend = path.resolve(__dirname, '..', '..', '..', 'backend');
    expect(resolveTestFilesDir()).toBe(path.join(repoBackend, 'files'));
  });
});

describe('wipeAvatarsDir (GH #262 §6)', () => {
  const ORIGINAL = { ...process.env };
  let filesRoot: string;

  beforeEach(() => {
    delete process.env.SHARD_ID;
    filesRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'files-dir-test-'));
    process.env.TEST_FILES_DIR = filesRoot;
  });

  afterEach(() => {
    fs.rmSync(filesRoot, { recursive: true, force: true });
    process.env = { ...ORIGINAL };
  });

  it('removes the avatars dir (and only that) under FILES_DIR', () => {
    const avatars = path.join(filesRoot, 'avatars');
    const keep = path.join(filesRoot, 'other');
    fs.mkdirSync(avatars, { recursive: true });
    fs.mkdirSync(keep, { recursive: true });
    fs.writeFileSync(path.join(avatars, 'portrait.png'), 'bytes');

    wipeAvatarsDir();

    expect(fs.existsSync(avatars)).toBe(false);
    expect(fs.existsSync(keep)).toBe(true); // siblings untouched
  });

  it('is a no-op when the avatars dir is absent (force:true)', () => {
    expect(() => wipeAvatarsDir()).not.toThrow();
    expect(fs.existsSync(path.join(filesRoot, 'avatars'))).toBe(false);
  });
});
